/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
import java.awt.Font;

public class main_cadenas extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main_cadenas.class.getName());
    Combinaison combiTestee;
    Combinaison combiSecrete;
    int nbCourant1 = 0;
    int nbCourant2 = 0;
    int nbCourant3 = 0;
    int nbCourant4 = 0;
    private int nbTentatives=0;
    /**
     * Creates new form main_cadenas
     */
    public main_cadenas() {
        int a,b,c,d;
        initComponents();
        a=(int) (Math.random()*10);
        b=(int) (Math.random()*10);
        c=(int) (Math.random()*10);
        d=(int) (Math.random()*10);      
        combiSecrete = new Combinaison(a, b, c, d);
        nbTentatives = 0;
    texte_tentatives.setText("0 sur 5");
    texte_chiffre_0.setFont(new Font("Arial", Font.BOLD, 24));
    texte_chiffre_1.setFont(new Font("Arial", Font.BOLD, 24));
    texte_chiffre_2.setFont(new Font("Arial", Font.BOLD, 24));
    texte_chiffre_3.setFont(new Font("Arial", Font.BOLD, 24));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl_nbchiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nbchiffres_haut = new javax.swing.JLabel();
        texte_lbl_nbchiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

                        texte_chiffre_0.setText("0");
                        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 20, 30));

                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setAlignmentX(0.5F);
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 20, 30));

                        texte_lbl_nbchiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nbchiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

                        texte_lbl_nbchiffres_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nbchiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                        texte_lbl_nbchiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nbchiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 32, 33));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

                        texte_score.setText("Tentatives");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

                        texte_tentatives.setText("0 sur 5");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        combiTestee = new Combinaison(nbCourant1, nbCourant2, nbCourant3, nbCourant4);

    int[] resultat = combiTestee.comparer(combiSecrete);//Donc créer autre endroit, condition si bonne combi
    nbTentatives++;
    texte_tentatives.setText(nbTentatives +"sur 5");
    
    texte_nb_chiffres_exacts.setText(resultat[0] +"");
    texte_nb_chiffres_haut.setText(resultat[1]+"");
    texte_nb_chiffres_bas.setText(resultat[2]+"");
    
    if (resultat[0]==4) {
        javax.swing.JOptionPane.showMessageDialog(this,"Bravo la combinaison a ete trouvée !");
    }
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        nbTentatives =0;
        texte_tentatives.setText("0 sur 5");
        texte_chiffre_0.setText(0+"");
        texte_chiffre_1.setText(0+"");
        texte_chiffre_2.setText(0+"");
        texte_chiffre_3.setText(0+"");
        texte_nb_chiffres_exacts.setText(0+"");
        texte_nb_chiffres_haut.setText(0+"");
        texte_nb_chiffres_bas.setText(0+"");
         int a = (int)(Math.random()*10);
         int b = (int)(Math.random()*10);
         int c = (int)(Math.random()*10);
         int d = (int)(Math.random()*10);
         nbCourant1=0;
         nbCourant2=0;
         nbCourant3=0;
         nbCourant4=0;

    combiSecrete = new Combinaison(a, b, c, d);
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
       if (nbCourant4>0){
           nbCourant4--;
       }
       else {
           nbCourant4=9;
       }
       texte_chiffre_3.setText(nbCourant4+"");
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        if (nbCourant3>0){
           nbCourant3--;
       }
       else {
           nbCourant3=9;
       }
       texte_chiffre_2.setText(nbCourant3+"");
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        if (nbCourant2>0){
           nbCourant2--;
       }
       else {
           nbCourant2=9;
       }
       texte_chiffre_1.setText(nbCourant2+"");
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
       if (nbCourant4<9){
    nbCourant4++;
}
else {
      nbCourant4=0;
}
texte_chiffre_3.setText(nbCourant4+"");
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        if (nbCourant3<9){
    nbCourant3++;
}
else {
      nbCourant3=0;
}
texte_chiffre_2.setText(nbCourant3+"");
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        if (nbCourant2<9){
    nbCourant2++;
}
else {
      nbCourant2=0;
}
texte_chiffre_1.setText(nbCourant2+"");
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
       if (nbCourant1<9){
    nbCourant1++;
}
else {
      nbCourant1=0;
}
texte_chiffre_0.setText(nbCourant1+"");
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        if (nbCourant1>0){
           nbCourant1--;
       }
       else {
           nbCourant1=9;
       }
       texte_chiffre_0.setText(nbCourant1+"");
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new main_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nbchiffres_bas;
    private javax.swing.JLabel texte_lbl_nbchiffres_exacts;
    private javax.swing.JLabel texte_lbl_nbchiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
