package lightoff_bourguet_version_graphique;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JButton;
import java.awt.GridLayout;
import lightoff_bourguet_version_console.GrilleDeJeu;


/**
 *
 * @author romai
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    
    // === Attributs migrés depuis Partie ===
    private GrilleDeJeu grille;
    private int nbCoups;
    
    
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
    initComponents(); // initialise les composants NetBeans

    int nbLignes = 10;
    int nbColonnes = 10;

    // Initialisation de la grille logique
    this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
    this.nbCoups = 0;

    // Configuration du panneau vertical existant créé par NetBeans
    PanneauBoutonsVert.setLayout(new GridLayout(nbLignes, 1));

    // Création des boutons verticaux (une ligne = un bouton)
    for (int i = 0; i < nbLignes; i++) {
        JButton bouton_ligne = new JButton("Ligne " + i);
        final int index = i; // nécessaire pour l'action
        bouton_ligne.addActionListener(e -> {
            grille.activerLigneDeCellules(index); // inverse la ligne correspondante
            repaint(); // rafraîchit l'affichage
            apresAction(); // incrémente le compteur et vérifie la victoire
        });
        PanneauBoutonsVert.add(bouton_ligne);
    }

    // Ajuste la taille et rafraîchit l'affichage
    this.pack();
    this.revalidate();

    // Initialisation de la partie
    initialiserPartie();

    // Initialisation de la grille graphique principale
    initialiserGrille(nbLignes, nbColonnes);
}
    
private void apresAction() {
    nbCoups++;
    NbrTentatives.setText(String.valueOf(nbCoups));

    if (grille.cellulesToutesEteintes()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Bravo ! Victoire en " + nbCoups + " coups");
    }
}


    public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
        nbCoups = 0;
    }

    private void initialiserGrille(int nbLignes, int nbColonnes) {

        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique boutonCellule =
                new CelluleGraphique(
                    grille.getCellule(i, j),
                    40,
                    40
                );
                PanneauGrille.add(boutonCellule);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        btnLigne0 = new javax.swing.JButton();
        btnDiagMont = new javax.swing.JButton();
        btnDiagDesc = new javax.swing.JButton();
        Tentatives = new javax.swing.JLabel();
        NbrTentatives = new javax.swing.JLabel();
        btnColonne0 = new javax.swing.JButton();
        PanneauBoutonsVert = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(102, 0, 255));
        PanneauGrille.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        btnLigne0.setText("Inverser Ligne 0");
        btnLigne0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        btnDiagMont.setText("inverser DiagMont");
        btnDiagMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagMontActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagMont, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 33, 110, 20));

        btnDiagDesc.setText("InverserDiagDesc");
        btnDiagDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagDescActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        Tentatives.setText("Tentatives : ");
        getContentPane().add(Tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        NbrTentatives.setText("0");
        getContentPane().add(NbrTentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        btnColonne0.setText("Inverser Colonne 0");
        btnColonne0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColonne0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColonne0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        PanneauBoutonsVert.setBackground(new java.awt.Color(51, 0, 255));
        PanneauBoutonsVert.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout PanneauBoutonsVertLayout = new javax.swing.GroupLayout(PanneauBoutonsVert);
        PanneauBoutonsVert.setLayout(PanneauBoutonsVertLayout);
        PanneauBoutonsVertLayout.setHorizontalGroup(
            PanneauBoutonsVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        PanneauBoutonsVertLayout.setVerticalGroup(
            PanneauBoutonsVertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigne0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne0ActionPerformed
      this.grille.activerLigneDeCellules(0); 
      repaint(); 
      apresAction();
    }//GEN-LAST:event_btnLigne0ActionPerformed

    private void btnDiagMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagMontActionPerformed
       this.grille.activerDiagonaleMontante(); 
       repaint(); 
       apresAction();
    }//GEN-LAST:event_btnDiagMontActionPerformed

    private void btnDiagDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagDescActionPerformed
        this.grille.activerDiagonaleDescendante();
        repaint();
        apresAction();
    }//GEN-LAST:event_btnDiagDescActionPerformed

    private void btnColonne0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColonne0ActionPerformed
        this.grille.activerColonneDeCellules(0);
        repaint(); 
        apresAction();
    }//GEN-LAST:event_btnColonne0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NbrTentatives;
    private javax.swing.JPanel PanneauBoutonsVert;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JLabel Tentatives;
    private javax.swing.JButton btnColonne0;
    private javax.swing.JButton btnDiagDesc;
    private javax.swing.JButton btnDiagMont;
    private javax.swing.JButton btnLigne0;
    // End of variables declaration//GEN-END:variables
}
