/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class Interface extends javax.swing.JFrame {
private Questions[] listeQuestions;
private int indexQuestion = 0;
private int indexQuestionCourante = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
int compteur=0;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        zone_de_texte.setVisible(false);
     
    listeQuestions = new Questions[] {
        new Questions("Capital de la France ?", "Paris", "Londres", "Madrid", "Berlin", 1),
        new Questions("2 + 2 ?", "3", "4", "5", "6", 2),
        new Questions("Couleur du ciel ?", "Vert", "Bleu", "Rouge", "Orange", 2),
        new Questions("qui est le plus fort?","Pogi","VDP","Pinot","RomainBardet_Jel'aime",4),
        new Questions("meilleur club de foot?", "FC Marseille","QSG", "L'OL","FC Lapaillade",3),
    };
    
    
}
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zone_de_texte = new javax.swing.JLabel();
        proposition1 = new javax.swing.JButton();
        proposition2 = new javax.swing.JButton();
        proposition3 = new javax.swing.JButton();
        proposition4 = new javax.swing.JButton();
        QuestionSuivante = new javax.swing.JButton();
        ReponseVouF = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zone_de_texte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        zone_de_texte.setText("Question 1 :");
        getContentPane().add(zone_de_texte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        proposition1.setText("1");
        getContentPane().add(proposition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        proposition2.setText("2");
        proposition2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposition2ActionPerformed(evt);
            }
        });
        getContentPane().add(proposition2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        proposition3.setText("jButton2");
        proposition3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposition3ActionPerformed(evt);
            }
        });
        getContentPane().add(proposition3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        proposition4.setText("jButton3");
        getContentPane().add(proposition4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        QuestionSuivante.setText("jButton1");
        getContentPane().add(QuestionSuivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        ReponseVouF.setText("jLabel1");
        getContentPane().add(ReponseVouF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        Score.setText("jLabel1");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proposition2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposition2ActionPerformed
zone_de_texte.setVisible(true);
if (compteur==0) zone_de_texte.setText("helloo");
if (compteur==1) zone_de_texte.setText("bonjour encore");
if (compteur==2) zone_de_texte.setText("t'abuses c'est trop");
if (compteur==3) zone_de_texte.setEnabled(false);
 compteur++;
        // TODO add your handling code here:
    }//GEN-LAST:event_proposition2ActionPerformed

    private void proposition3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposition3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proposition3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JLabel ReponseVouF;
    private javax.swing.JLabel Score;
    private javax.swing.JButton proposition1;
    private javax.swing.JButton proposition2;
    private javax.swing.JButton proposition3;
    private javax.swing.JButton proposition4;
    private javax.swing.JLabel zone_de_texte;
    // End of variables declaration//GEN-END:variables
}
